[tool.ruff]
line-length = 100
target-version = "py312"
extend-include = ["*.ipynb"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
line-ending = "lf"
docstring-code-format = true
