name: Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT"
  push:
    branches:
      - master-pub

permissions: {} # no permissions needed

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master-pub

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' --insecure --exclude "https://pastepixel.com/image/....png" --exclude "http://eturnbull.ca/pythonlibs/" --exclude "https://twitter.com/*" --exclude-all-private
          fail: true
