name: CI
on:
  push:
    branches:
      - master-pub
  workflow_dispatch:

permissions: {}

jobs:
  update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master-pub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run script
        run: |
          python ./.github/scripts/update_readme_tree.py

      - name: Setup git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit changes using --porcelain
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add README.md
            git commit -m "Update README.md tree"
            git push --set-upstream origin master-pub
          else
            echo "No changes to commit"
          fi

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master-pub
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.1

  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master-pub

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' --insecure --exclude-all-private
          fail: true
