name: CI
on:
  push:
    branches:
      - master-pub
  workflow_dispatch:

permissions: {}

jobs:
  update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master-pub

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run script
        run: |
          python ./scripts/update_readme_tree.py

      - name: Setup git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit changes using --porcelain
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add README.md
            git commit -m "Update README.md tree"
            git push --set-upstream origin master-pub
          else
            echo "No changes to commit"
          fi

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master-pub
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1

  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master-pub

      # - name: Restore lychee cache
      #   id: restore-cache
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: .lycheecache
      #     key: cache-lychee-${{ github.sha }}
      #     restore-keys: cache-lychee-

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' --insecure --exclude-all-private --cache --max-cache-age 3d --suggest --archive wayback --github-token ${{ secrets.GITHUB_TOKEN }}  --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0" --max-concurrency 5

      # - name: Save lychee cache
      #   uses: actions/cache/save@v4
      #   if: always()
      #   with:
      #     path: .lycheecache
      #     key: ${{ steps.restore-cache.outputs.cache-primary-key }}
